export const ANIMAL_DATA = {
  species: [
    { value: "cachorro", label: "Cachorro" },
    { value: "gato", label: "Gato" },
    { value: "coelho", label: "Coelho" },
    { value: "passaro", label: "Pássaro" },
    { value: "roedor", label: "Roedor" },
    { value: "outro", label: "Outro" },
  ],

  breeds: {
    cachorro: [
      "Vira-lata",
      "Poodle",
      "Shih Tzu",
      "Bulldog",
      "Pastor Alemão",
      "Labrador",
      "Golden Retriever",
      "Cachorro d'água",
      "Pinscher",
      "Husky",
      "Dálmata",
      "Beagle",
      "Boxer",
      "Cocker Spaniel",
      "Lhasa Apso",
      "Maltês",
      "Schnauzer",
      "Rottweiler",
      "Pit Bull",
      "Outro",
    ],
    gato: [
      "Vira-lata",
      "Persa",
      "Siamês",
      "Maine Coon",
      "Bengala",
      "Azul Russo",
      "Ragdoll",
      "Sphynx",
      "Angora",
      "Abissínio",
      "Burmês",
      "British Shorthair",
      "Bombay",
      "Manx",
      "Mau Egípcio",
      "Gato de Bengala",
      "Outro",
    ],
    coelho: [
      "Angorá",
      "Holandês",
      "Hipster",
      "Florida White",
      "Belier",
      "Chinchila",
      "Outro",
    ],
    passaro: [
      "Canário",
      "Periquito",
      "Calopsita",
      "Arara",
      "Papagaio",
      "Pombinha",
      "Curió",
      "Outro",
    ],
    roedor: [
      "Hamster Sírio",
      "Hamster Russo",
      "Porquinho-da-Índia",
      "Rato",
      "Camundongo",
      "Chinchila",
      "Outro",
    ],
    outro: [
      "Peixes",
      "Réptil",
      "Inseto",
      "Outro",
    ],
  },

  colors: [
    "Branco",
    "Preto",
    "Marrom",
    "Cinza",
    "Caramelo",
    "Amarelo",
    "Dourado",
    "Vermelho",
    "Creme",
    "Malhado",
    "Mesclado",
    "Tricolor",
    "Bicolor",
    "Outro",
  ],

  sex: [
    { value: "Macho", label: "Macho" },
    { value: "Fêmea", label: "Fêmea" },
    { value: "Desconhecido", label: "Desconhecido" },
  ],

  size: [
    { value: "Pequeno", label: "Pequeno" },
    { value: "Médio", label: "Médio" },
    { value: "Grande", label: "Grande" },
    { value: "Gigante", label: "Gigante" },
  ],

  status: [
    { value: "Disponível", label: "Disponível" },
    { value: "Em processo", label: "Em processo" },
    { value: "Adotado", label: "Adotado" },
  ],
} as const;

