export const ANIMAL_DATA = {
    species: [
        { value: "cachorro", label: "Cachorro" },
        { value: "gato", label: "Gato" },
        { value: "coelho", label: "Coelho" },
        { value: "passaro", label: "Passaro" },
        { value: "roedor", label: "Roedor" },
        { value: "outro", label: "Outro" },
    ],

    breeds: {
        cachorro: [
            "Vira-lata",
            "Poodle",
            "Shih Tzu",
            "Bulldog",
            "Pastor Alemao",
            "Labrador",
            "Golden Retriever",
            "Cachorro d'agua",
            "Pinscher",
            "Husky",
            "Dalmata",
            "Beagle",
            "Boxer",
            "Cocker Spaniel",
            "Lhasa Apso",
            "Maltes",
            "Schnauzer",
            "Rottweiler",
            "Pit Bull",
            "Outro",
        ],
        gato: [
            "Vira-lata",
            "Persa",
            "Siames",
            "Maine Coon",
            "Bengala",
            "Azul Russo",
            "Ragdoll",
            "Sphynx",
            "Angora",
            "Abissinio",
            "Burmes",
            "British Shorthair",
            "Bombay",
            "Manx",
            "Mau Egipcio",
            "Gato de Bengala",
            "Outro",
        ],
        coelho: ["Angora", "Holandes", "Florida White", "Belier", "Chinchila", "Outro"],
        passaro: ["Canario", "Periquito", "Calopsita", "Arara", "Papagaio", "Pombinha", "Curio", "Outro"],
        roedor: ["Hamster Sirio", "Hamster Russo", "Porquinho-da-India", "Rato", "Camundongo", "Chinchila", "Outro"],
        outro: ["Peixes", "Reptil", "Inseto", "Outro"],
    },

    colors: [
        "Branco",
        "Preto",
        "Marrom",
        "Cinza",
        "Caramelo",
        "Amarelo",
        "Dourado",
        "Vermelho",
        "Creme",
        "Malhado",
        "Mesclado",
        "Tricolor",
        "Bicolor",
        "Outro",
    ],

    sex: [
        { value: "Macho", label: "Macho" },
        { value: "Femea", label: "Femea" },
        { value: "Desconhecido", label: "Desconhecido" },
    ],

    size: [
        { value: "Pequeno", label: "Pequeno" },
        { value: "Medio", label: "Medio" },
        { value: "Grande", label: "Grande" },
        { value: "Gigante", label: "Gigante" },
    ],

    status: [
        { value: "Disponivel", label: "Disponivel" },
        { value: "Em processo", label: "Em processo" },
        { value: "Adotado", label: "Adotado" },
    ],
} as const;
